// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: todoproto/todogrpc.proto

package todoproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewToDo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task   string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	UserID int32  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *NewToDo) Reset() {
	*x = NewToDo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoproto_todogrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewToDo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewToDo) ProtoMessage() {}

func (x *NewToDo) ProtoReflect() protoreflect.Message {
	mi := &file_todoproto_todogrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewToDo.ProtoReflect.Descriptor instead.
func (*NewToDo) Descriptor() ([]byte, []int) {
	return file_todoproto_todogrpc_proto_rawDescGZIP(), []int{0}
}

func (x *NewToDo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *NewToDo) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ToDo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task   string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	UserID int32  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Done   bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	TodoID string `protobuf:"bytes,4,opt,name=todoID,proto3" json:"todoID,omitempty"`
}

func (x *ToDo) Reset() {
	*x = ToDo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoproto_todogrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDo) ProtoMessage() {}

func (x *ToDo) ProtoReflect() protoreflect.Message {
	mi := &file_todoproto_todogrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDo.ProtoReflect.Descriptor instead.
func (*ToDo) Descriptor() ([]byte, []int) {
	return file_todoproto_todogrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ToDo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ToDo) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ToDo) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ToDo) GetTodoID() string {
	if x != nil {
		return x.TodoID
	}
	return ""
}

var File_todoproto_todogrpc_proto protoreflect.FileDescriptor

var file_todoproto_todogrpc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x6f, 0x64, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x6f, 0x64, 0x6f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x44, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5e, 0x0a, 0x04,
	0x54, 0x6f, 0x44, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x64, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x64, 0x6f, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x64, 0x6f, 0x49, 0x44, 0x32, 0x42, 0x0a, 0x08,
	0x54, 0x6f, 0x64, 0x6f, 0x47, 0x72, 0x70, 0x63, 0x12, 0x36, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x44, 0x6f, 0x12, 0x12, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x44, 0x6f, 0x1a, 0x0f, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x22, 0x00,
	0x42, 0x19, 0x5a, 0x17, 0x6f, 0x6f, 0x66, 0x70, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_todoproto_todogrpc_proto_rawDescOnce sync.Once
	file_todoproto_todogrpc_proto_rawDescData = file_todoproto_todogrpc_proto_rawDesc
)

func file_todoproto_todogrpc_proto_rawDescGZIP() []byte {
	file_todoproto_todogrpc_proto_rawDescOnce.Do(func() {
		file_todoproto_todogrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_todoproto_todogrpc_proto_rawDescData)
	})
	return file_todoproto_todogrpc_proto_rawDescData
}

var file_todoproto_todogrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_todoproto_todogrpc_proto_goTypes = []interface{}{
	(*NewToDo)(nil), // 0: todoproto.NewToDo
	(*ToDo)(nil),    // 1: todoproto.ToDo
}
var file_todoproto_todogrpc_proto_depIdxs = []int32{
	0, // 0: todoproto.TodoGrpc.CreateNewToDo:input_type -> todoproto.NewToDo
	1, // 1: todoproto.TodoGrpc.CreateNewToDo:output_type -> todoproto.ToDo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todoproto_todogrpc_proto_init() }
func file_todoproto_todogrpc_proto_init() {
	if File_todoproto_todogrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todoproto_todogrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewToDo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoproto_todogrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todoproto_todogrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoproto_todogrpc_proto_goTypes,
		DependencyIndexes: file_todoproto_todogrpc_proto_depIdxs,
		MessageInfos:      file_todoproto_todogrpc_proto_msgTypes,
	}.Build()
	File_todoproto_todogrpc_proto = out.File
	file_todoproto_todogrpc_proto_rawDesc = nil
	file_todoproto_todogrpc_proto_goTypes = nil
	file_todoproto_todogrpc_proto_depIdxs = nil
}
